### ISSUE TITLE
Viewport sized incorrectly Google Lighthouse error

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#1]
Honestly, I'm not sure what this warning is about.  Lighthouse doesn't give any specifics which makes it hard to track down, and I wasn't able to get rid of the warning after trying some different sizes / widths to elements like `<article>` and others with CSS.

I ran the site through axe and it didn't turn up anything about the viewport / size, so I guess that as long as you feel everything is pretty readable, and an accessibility tool like axe isn't worried, I'm not too worried either.  If you do ever figure out what it is, I would be interested in knowing!

**Comment by awisnicki** [comment]
Thanks for this! Yes, I've made several attempts to figure this out and, though it seems very simple, I've just not been able to sort this out. Everything appears to be working properly and is sizing correctly on screen – including tests I did on various devices – so this was really just me seeing if there was something I was overlooking. However, I think we can call it a wrap on this, so please feel free to close this issue once you've seen my comment.
