### ISSUE TITLE
CSS minifiction

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#14]
You have some CSS which is all minified into one long line. As far as serving to the web is concerned, this is a good thing!  But as far as development goes, this is a lot of work for you to edit.  This is another check in the "web framework or generator" argument's camp, since most of those will let you work on a "pretty" CSS (or even SCSS!) file and then when you deploy / serve the website, it will crunch it into a minified CSS file for you.

I'm mentioning this because I wanted to make a change to your CSS while I was working on that viewport issue and it was very difficult for me to find what it was I wanted to change.  I imagine that you have this problem, also, when you want to edit the website.

**Comment by awisnicki** [comment]
Thanks for making this point. Duly noted. Right now when I want to edit CSS, I work directly in the browser. (Note: Firefox automatically prettifies the CSS, while Chrome dev tools has a "Format" button that does the same thing, so the minification isn't an issue). Once I've sorted out the code I need, I move it into a dev/unminified version of the given CSS file, then I minify that using a basic online minifier and use the minified version of the file online. The workflow here therefore is a touch clunky, but isn't that bad and works well enough for me. That said, I of course wouldn't mind an easier workflow and, per our discussion in email and your suggestion in one of the other issues, am definitely ready to look into a static site generator and other such options.

Please feel free to close this issue once you've seen my response.

**Comment by jduss4** [comment]
Makes sense!  Sounds like it is working fine for you now!  :)
