### ISSUE TITLE
Mix of spaces and tabs

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#6]
Okay this is a minor quibble in the grand scheme of things, but ideally your editor will be set up to use either spaces or tabs and then make sure it keeps happening!  This is an easy fix, as a lot of editors will allow you to select an entire document and switch tabs -> spaces or vice versa, whichever way you decide to go.

It's also not something you have to fix if you don't want to, but it jumped out at me when I was looking at the code.

**Comment by awisnicki** [comment]
I've sorted this out using VSC per our email exchange. In particular [this page](https://stackoverflow.com/questions/33974681/how-can-i-convert-tabs-to-spaces-and-vice-versa-in-an-existing-file/37509777#37509777), which you recommended, proved quite helpful. I fixed both existing pages and set it up to automatically set tab at four spaces going forward. Thanks again!
