### ISSUE TITLE
JavaScript loading

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#8]
I see that you are loading the JavaScript after the rest of the page loads.  I confess I don't entirely understand what you are doing here with this code:

```
if (window.addEventListener)
    window.addEventListener("load", downloadJSAtOnload, false);
else if (window.attachEvent)
    window.attachEvent("onload", downloadJSAtOnload);
else window.onload = downloadJSAtOnload;
```

If your goal is just to make sure javascript is fired off after the page loads, then you have a couple options.

Since you have jquery on this page already, you could rely on jquery to help you load: https://learn.jquery.com/using-jquery-core/document-ready/

Or you could rely on non-jquery methods, which I see you have at the very end of your existing code:

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload

Typically, rather than load javascript elsewhere on the same page, you could include a JS file in your HTML, and then that file itself would have a line like below, and everything inside of it would be loaded later.
```
$(document).ready(function() {
    // code
});
````

It's not critical or anything, but it's something to think about and it would help clean up the JS on your HTML pages as well.

**Comment by awisnicki** [comment]
This one turned out to be much easier than anticipated. I've gone with the jquery solution, the first solution above. Thanks for the help with this!
